name: trackstar
description: "A music recommendation app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/TRACKSTAR variant sans typo 1.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/app_data.db
    - assets/images/